apiVersion: v2
name: warehouse
description: A Helm chart for the Warehouse application
type: application
version: 0.1.1
appVersion: "0.1.1"
dependencies:
  - name: postgresql
    repository: "https://charts.bitnami.com/bitnami"
    version: "10.3.13"
